### ISSUE TITLE
Gray16,GrayS support

### ISSUE THREAD

**Issue by 2ndR** [Kiyamou/VapourSynth-AreaResize#1]
Requires processing of Luma only

**Comment by Kiyamou** [comment]
Gray support has been added.
Maybe can test it :)

**Comment by 2ndR** [comment]
I've tried 1920x1080>1280x720, 960x540>640x360 in GrayS with VapourSynth R52 and it seems to work fine!
Thank you for your support!

**Comment by Kiyamou** [comment]
Sounds great. Thank you for your suggestion, too.
